In [1]:
import numpy as np

In [9]:
def blsys(B, C):
    def f(x, u):
        return B @ x + C @ u
    return f

In [18]:
def cd(a):
    def f(k, l):
        return k ** a * l ** (1 - a)
    return f

cd(0.3)(2, 1)

1.2311444133449163

In [4]:
B = np.array([
    [0.9, 0.0],
    [0.0, 0.9]
])
B

array([[0.9, 0. ],
       [0. , 0.9]])

In [5]:
np.diag([0.9, 0.9])

array([[0.9, 0. ],
       [0. , 0.9]])

In [6]:
0.9 * np.eye(2)

array([[0.9, 0. ],
       [0. , 0.9]])

In [8]:
C = np.eye(2)
C

array([[1., 0.],
       [0., 1.]])

In [13]:
f = blsys(B, C)

In [15]:
x0 = np.array([0, 0])
u0 = np.array([1, 1])
x1 = f(x0, u0)
x1

array([1., 1.])

In [36]:
from numpy.random import randn

def simulate(g, x0, T):
    x = np.empty((T, len(x0), 1))
    x[0] = x0.reshape((2, 1))
    for i in range(T-1):
        u = randn(2, 1)
        x[i+1] = g(x[0], u)
    return x

In [35]:
simulate(f, x0, 100)

array([[[ 0.00000000e+00],
        [ 0.00000000e+00]],

       [[ 1.63970526e-01],
        [-1.36767027e+00]],

       [[ 8.64260253e-01],
        [ 1.04648096e+00]],

       [[ 8.08100083e-01],
        [ 9.05913246e-01]],

       [[ 4.13872886e-01],
        [ 1.80785069e+00]],

       [[-7.44323709e-03],
        [ 1.09154207e+00]],

       [[ 3.66135085e-02],
        [ 7.66674035e-01]],

       [[ 6.41915262e-01],
        [ 1.74213462e+00]],

       [[-1.10800858e-01],
        [ 6.95024162e-01]],

       [[ 1.48790126e+00],
        [-3.91818374e-03]],

       [[ 1.32443152e+00],
        [-5.02919439e-01]],

       [[-1.59885782e-01],
        [ 1.48186131e+00]],

       [[-9.71389143e-01],
        [-2.98808399e-01]],

       [[ 8.87932070e-01],
        [ 7.88550455e-01]],

       [[-5.18628875e-01],
        [ 8.69996237e-01]],

       [[-8.64245960e-01],
        [ 2.74435893e-01]],

       [[ 1.29916162e+00],
        [ 7.96495169e-01]],

       [[ 3.18951580e-01],
        [-5.29017656e

In [33]:
randn(2, 1)

array([[-0.72509564],
       [ 1.40622591]])